NegativeFeel.create(negative_feel_name: '不安')
NegativeFeel.create(negative_feel_name: '苦しい')
NegativeFeel.create(negative_feel_name: '心配')
NegativeFeel.create(negative_feel_name: '憂うつ')
NegativeFeel.create(negative_feel_name: '不快感')
NegativeFeel.create(negative_feel_name: '罪悪感')
NegativeFeel.create(negative_feel_name: '緊張')
NegativeFeel.create(negative_feel_name: '疲労感')
NegativeFeel.create(negative_feel_name: '落ち込む')
NegativeFeel.create(negative_feel_name: '悲しい')
NegativeFeel.create(negative_feel_name: 'さみしい')
NegativeFeel.create(negative_feel_name: '動揺している')
NegativeFeel.create(negative_feel_name: '怒り')
NegativeFeel.create(negative_feel_name: '嫌悪')

PositiveFeel.create(positive_feel_name: '愛されている')
PositiveFeel.create(positive_feel_name: '感謝している')
PositiveFeel.create(positive_feel_name: '自由')
PositiveFeel.create(positive_feel_name: 'よろこび')
PositiveFeel.create(positive_feel_name: '落ち着き')
PositiveFeel.create(positive_feel_name: '充足感')
PositiveFeel.create(positive_feel_name: '好奇心')
PositiveFeel.create(positive_feel_name: '高揚感')
PositiveFeel.create(positive_feel_name: '自信')
PositiveFeel.create(positive_feel_name: '安心')
PositiveFeel.create(positive_feel_name: 'やる気がある')
PositiveFeel.create(positive_feel_name: '熱心')
PositiveFeel.create(positive_feel_name: '思いやり')
PositiveFeel.create(positive_feel_name: '感心')

DistortionList.create(distortion_name: '白黒思考' )
DistortionList.create(distortion_name: '過度な一般化') 
DistortionList.create(distortion_name: '心のフィルター') 
DistortionList.create(distortion_name: 'マイナス化思考' )
DistortionList.create(distortion_name: '読心術' )
DistortionList.create(distortion_name: '運命の先読み') 
DistortionList.create(distortion_name: '破滅化' )
DistortionList.create(distortion_name: '感情的決めつけ' )
DistortionList.create(distortion_name: 'べき思考' )
DistortionList.create(distortion_name: 'レッテル貼り') 
DistortionList.create(distortion_name: '内なる批評家' )
DistortionList.create(distortion_name: '他人批判')